# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sohamjobanputraprominentpixel
# "service" is the name of this project. This will also be added to your AWS resource names.
service: startup-template

provider:
  name: aws
  runtime: nodejs22.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  api:
    timeout: 900
    handler: index.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
  - serverless-offline-watcher

custom:
  serverless-offline-watcher:
    - path:
        - src/**/**
        - index.ts
      hook:
        - offline:functionsUpdated
      command: "echo Received %WATCHER_EVENT_TYPE% event for %WATCHER_EVENT_PATH%"
